### ISSUE TITLE
Environment appended to the files names.

### ISSUE THREAD

**Issue by lemattma** [rjocoleman/capistrano-upload-config#10]
Is there any way to avoid the env name to be added to the file names?

```
WARN Not found: config/database.production.yml
WARN Not found: config/application.production.yml
WARN Not found: config/secrets.production.yml
```

I need:

```
WARN Not found: config/database.yml
WARN Not found: config/application.yml
WARN Not found: config/secrets.yml
```

Thanks!

**Comment by frontandstart** [comment]
@lemattma so logic of this gem look like that:
 on localhost you have two version of shared files for ex.:
(1) database.yml and  (2)database.production.ml
First(1) file is database file that you use only for local development and you local database
so Second (2) file will be copy to shared folder on server with normal name like: database.yml
my capistrano logs:
```
DEBUG [bd8ab15e] Finished in 0.090 seconds with exit status 0 (successful).
INFO Uploading config config/database.production.yml as config/database.yml
DEBUG Uploading /home/weso/git.itweso.at/shared/config/database.yml 0.0%
INFO Uploading /home/weso/git.itweso.at/shared/config/database.yml 100.0%
INFO Uploading config config/secrets.production.yml as config/secrets.yml
```

**Comment by frontandstart** [comment]
don't forget create shared dirs like shared/config
before start uploading using this gem
